# Generated by Django 4.0.1 on 2022-01-23 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assetsmgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='assets',
            name='amount_purchased',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assets',
            name='current_value_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='assets',
            name='date_disposed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assets',
            name='is_disposed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='photo_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='assets',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='warranty_end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='brand',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
