# Generated by Django 4.0.1 on 2022-01-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsmgt', '0002_rename_brand_id_assets_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='is_disposed',
            field=models.BigIntegerField(default=0),
        ),
    ]
