# Generated by Django 4.0.1 on 2022-01-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetsmgt', '0004_alter_assets_is_disposed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='asset_name',
            new_name='assetname',
        ),
    ]
