# Generated by Django 4.0.1 on 2022-02-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsmgt', '0005_rename_asset_name_assets_assetname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=100)),
                ('assets_location', models.CharField(max_length=100)),
                ('date_issued', models.DateField()),
                ('purpose', models.TextField()),
                ('update_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=255)),
                ('update_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('updated_at', models.DateField()),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.companybranch')),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.department')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('remark', models.TextField()),
                ('date_assigned', models.DateField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.assets')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.companybranch')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_from', models.IntegerField()),
                ('transferred_to', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('remark', models.TextField()),
                ('date_transferred', models.DateField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.assets')),
            ],
        ),
    ]
