# Generated by Django 4.0.1 on 2022-02-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsmgt', '0006_assetslocation_companybranch_department_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('fixing_price', models.FloatField()),
                ('fixed_by', models.IntegerField()),
                ('date_fixed', models.DateField()),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.assets')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('date_Supplied', models.DateField()),
                ('cost', models.FloatField()),
                ('condition', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('supplier', models.IntegerField()),
                ('status', models.IntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.companybranch')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsmgt.category')),
            ],
        ),
    ]
